create table notes (
    id integer primary key generated by default as identity,
    name text not null,
    content text not null,
    modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    folderid integer references folders(id) on delete cascade
);